name: Monthly Check Series Production

on:
    schedule:
        - cron: '0 3 15 * *'
jobs:
    check_series_production:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run script
              run: python .github/scripts/main.py check-series-production
            - name: Commit changes
              run: |
                git config user.name ${{secrets.USER_NAME}}
                git config user.email ${{secrets.USER_EMAIL}}
                git add .
                git commit -m ":robot: Check series production"
                git push