name: Monthly Check Movie Collection

on:
    schedule:
        - cron: '0 5 15 * *'
    workflow_dispatch:

jobs:
    check_movie_collection:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run script
              env:
                  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
              run: python .github/scripts/main.py --check-movie-collection

            - name: Commit changes
              run: |
                git config user.name ${{ secrets.USER_NAME }}
                git config user.email ${{ secrets.USER_EMAIL }}
                git add .
                git commit -m ":robot: Check movie collection" || echo "No changes to commit"
                git push